services:
  network_project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network_project_container
    image: network_project_image
    tty: true
    volumes:
      - .:/home/ohsj3781/workspace
    user: "ohsj3781"
